-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('MANAGE_TENANT_SETTINGS', 'VIEW_ANALYTICS', 'CREATE_PRODUCT', 'UPDATE_PRODUCT', 'DELETE_PRODUCT', 'VIEW_PRODUCTS', 'MANAGE_ORDERS', 'VIEW_ORDERS');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'TENANT_OWNER', 'TENANT_ADMIN', 'INVENTORY_MANAGER', 'CUSTOMER');
